
import "./globals.css";
import { Raleway } from 'next/font/google';


const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-raleway'            
})



export const metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={raleway.variable}>
        {children}
      </body>
    </html>
  );
}
